-- =============================================
-- INSERTION DES DONNÉES RÉELLES (SPÉCIALITÉS ET MATIÈRES)
-- =============================================

-- 1. Insertion des Spécialités
INSERT INTO public.specialties (id, name, code, description) VALUES (1, 'BAKERY AND FOOD PROCESSING', 'SPEC1', 'Département BAKERY AND FOOD PROCESSING') ON CONFLICT DO NOTHING;
INSERT INTO public.specialties (id, name, code, description) VALUES (2, 'BUILDING SCIENCE AND TECHNOLOGY', 'SPEC2', 'Département BUILDING SCIENCE AND TECHNOLOGY') ON CONFLICT DO NOTHING;
INSERT INTO public.specialties (id, name, code, description) VALUES (3, 'CIVIL ENGINEERING TECHNOLOGY', 'SPEC3', 'Département CIVIL ENGINEERING TECHNOLOGY') ON CONFLICT DO NOTHING;
INSERT INTO public.specialties (id, name, code, description) VALUES (4, 'HÔTELLERIE : GESTION ET MANAGEMENT HÔTELIERS', 'SPEC4', 'Département HÔTELLERIE : GESTION ET MANAGEMENT HÔTELIERS') ON CONFLICT DO NOTHING;
INSERT INTO public.specialties (id, name, code, description) VALUES (5, 'HÔTELLERIE : MANAGEMENT ET TECHNIQUES D’HÉBERGEMENTS', 'SPEC5', 'Département HÔTELLERIE : MANAGEMENT ET TECHNIQUES D’HÉBERGEMENTS') ON CONFLICT DO NOTHING;
INSERT INTO public.specialties (id, name, code, description) VALUES (6, 'MECHANICAL CONSTRUCTION', 'SPEC6', 'Département MECHANICAL CONSTRUCTION') ON CONFLICT DO NOTHING;
INSERT INTO public.specialties (id, name, code, description) VALUES (7, 'MECHANICAL MANUFACTURING', 'SPEC7', 'Département MECHANICAL MANUFACTURING') ON CONFLICT DO NOTHING;
INSERT INTO public.specialties (id, name, code, description) VALUES (8, 'METAL CONSTRUCTION', 'SPEC8', 'Département METAL CONSTRUCTION') ON CONFLICT DO NOTHING;
INSERT INTO public.specialties (id, name, code, description) VALUES (9, 'NETWORKS AND SECURITY', 'SPEC9', 'Département NETWORKS AND SECURITY') ON CONFLICT DO NOTHING;
INSERT INTO public.specialties (id, name, code, description) VALUES (10, 'RESTAURATION : COMMERCIALISATION ET SERVICES DE RESTAURATION', 'SPEC10', 'Département RESTAURATION : COMMERCIALISATION ET SERVICES DE RESTAURATION') ON CONFLICT DO NOTHING;
INSERT INTO public.specialties (id, name, code, description) VALUES (11, 'RESTAURATION : GÉNIE CULINAIRE', 'SPEC11', 'Département RESTAURATION : GÉNIE CULINAIRE') ON CONFLICT DO NOTHING;
INSERT INTO public.specialties (id, name, code, description) VALUES (12, 'TELECOMMUNICATIONS', 'SPEC12', 'Département TELECOMMUNICATIONS') ON CONFLICT DO NOTHING;
INSERT INTO public.specialties (id, name, code, description) VALUES (13, 'TOPOGRAPHY', 'SPEC13', 'Département TOPOGRAPHY') ON CONFLICT DO NOTHING;
INSERT INTO public.specialties (id, name, code, description) VALUES (14, 'TOURISME : MANAGEMENT TOURISTIQUE', 'SPEC14', 'Département TOURISME : MANAGEMENT TOURISTIQUE') ON CONFLICT DO NOTHING;
INSERT INTO public.specialties (id, name, code, description) VALUES (15, 'URBAN PLANNING', 'SPEC15', 'Département URBAN PLANNING') ON CONFLICT DO NOTHING;

-- 2. Insertion des Classes (Exemple: Niveau 1 et 2 pour chaque spécialité)
INSERT INTO public.classes (id, name, level, specialty_id, capacity) VALUES (1, 'BAKERY AND FOOD PROCESSING - Niveau 1', 'L1', 1, 50) ON CONFLICT DO NOTHING;
INSERT INTO public.classes (id, name, level, specialty_id, capacity) VALUES (2, 'BAKERY AND FOOD PROCESSING - Niveau 2', 'L2', 1, 50) ON CONFLICT DO NOTHING;
INSERT INTO public.classes (id, name, level, specialty_id, capacity) VALUES (3, 'BUILDING SCIENCE AND TECHNOLOGY - Niveau 1', 'L1', 2, 50) ON CONFLICT DO NOTHING;
INSERT INTO public.classes (id, name, level, specialty_id, capacity) VALUES (4, 'BUILDING SCIENCE AND TECHNOLOGY - Niveau 2', 'L2', 2, 50) ON CONFLICT DO NOTHING;
INSERT INTO public.classes (id, name, level, specialty_id, capacity) VALUES (5, 'CIVIL ENGINEERING TECHNOLOGY - Niveau 1', 'L1', 3, 50) ON CONFLICT DO NOTHING;
INSERT INTO public.classes (id, name, level, specialty_id, capacity) VALUES (6, 'CIVIL ENGINEERING TECHNOLOGY - Niveau 2', 'L2', 3, 50) ON CONFLICT DO NOTHING;
INSERT INTO public.classes (id, name, level, specialty_id, capacity) VALUES (7, 'HÔTELLERIE : GESTION ET MANAGEMENT HÔTELIERS - Niveau 1', 'L1', 4, 50) ON CONFLICT DO NOTHING;
INSERT INTO public.classes (id, name, level, specialty_id, capacity) VALUES (8, 'HÔTELLERIE : GESTION ET MANAGEMENT HÔTELIERS - Niveau 2', 'L2', 4, 50) ON CONFLICT DO NOTHING;
INSERT INTO public.classes (id, name, level, specialty_id, capacity) VALUES (9, 'HÔTELLERIE : MANAGEMENT ET TECHNIQUES D’HÉBERGEMENTS - Niveau 1', 'L1', 5, 50) ON CONFLICT DO NOTHING;
INSERT INTO public.classes (id, name, level, specialty_id, capacity) VALUES (10, 'HÔTELLERIE : MANAGEMENT ET TECHNIQUES D’HÉBERGEMENTS - Niveau 2', 'L2', 5, 50) ON CONFLICT DO NOTHING;
INSERT INTO public.classes (id, name, level, specialty_id, capacity) VALUES (11, 'MECHANICAL CONSTRUCTION - Niveau 1', 'L1', 6, 50) ON CONFLICT DO NOTHING;
INSERT INTO public.classes (id, name, level, specialty_id, capacity) VALUES (12, 'MECHANICAL CONSTRUCTION - Niveau 2', 'L2', 6, 50) ON CONFLICT DO NOTHING;
INSERT INTO public.classes (id, name, level, specialty_id, capacity) VALUES (13, 'MECHANICAL MANUFACTURING - Niveau 1', 'L1', 7, 50) ON CONFLICT DO NOTHING;
INSERT INTO public.classes (id, name, level, specialty_id, capacity) VALUES (14, 'MECHANICAL MANUFACTURING - Niveau 2', 'L2', 7, 50) ON CONFLICT DO NOTHING;
INSERT INTO public.classes (id, name, level, specialty_id, capacity) VALUES (15, 'METAL CONSTRUCTION - Niveau 1', 'L1', 8, 50) ON CONFLICT DO NOTHING;
INSERT INTO public.classes (id, name, level, specialty_id, capacity) VALUES (16, 'METAL CONSTRUCTION - Niveau 2', 'L2', 8, 50) ON CONFLICT DO NOTHING;
INSERT INTO public.classes (id, name, level, specialty_id, capacity) VALUES (17, 'NETWORKS AND SECURITY - Niveau 1', 'L1', 9, 50) ON CONFLICT DO NOTHING;
INSERT INTO public.classes (id, name, level, specialty_id, capacity) VALUES (18, 'NETWORKS AND SECURITY - Niveau 2', 'L2', 9, 50) ON CONFLICT DO NOTHING;
INSERT INTO public.classes (id, name, level, specialty_id, capacity) VALUES (19, 'RESTAURATION : COMMERCIALISATION ET SERVICES DE RESTAURATION - Niveau 1', 'L1', 10, 50) ON CONFLICT DO NOTHING;
INSERT INTO public.classes (id, name, level, specialty_id, capacity) VALUES (20, 'RESTAURATION : COMMERCIALISATION ET SERVICES DE RESTAURATION - Niveau 2', 'L2', 10, 50) ON CONFLICT DO NOTHING;
INSERT INTO public.classes (id, name, level, specialty_id, capacity) VALUES (21, 'RESTAURATION : GÉNIE CULINAIRE - Niveau 1', 'L1', 11, 50) ON CONFLICT DO NOTHING;
INSERT INTO public.classes (id, name, level, specialty_id, capacity) VALUES (22, 'RESTAURATION : GÉNIE CULINAIRE - Niveau 2', 'L2', 11, 50) ON CONFLICT DO NOTHING;
INSERT INTO public.classes (id, name, level, specialty_id, capacity) VALUES (23, 'TELECOMMUNICATIONS - Niveau 1', 'L1', 12, 50) ON CONFLICT DO NOTHING;
INSERT INTO public.classes (id, name, level, specialty_id, capacity) VALUES (24, 'TELECOMMUNICATIONS - Niveau 2', 'L2', 12, 50) ON CONFLICT DO NOTHING;
INSERT INTO public.classes (id, name, level, specialty_id, capacity) VALUES (25, 'TOPOGRAPHY - Niveau 1', 'L1', 13, 50) ON CONFLICT DO NOTHING;
INSERT INTO public.classes (id, name, level, specialty_id, capacity) VALUES (26, 'TOPOGRAPHY - Niveau 2', 'L2', 13, 50) ON CONFLICT DO NOTHING;
INSERT INTO public.classes (id, name, level, specialty_id, capacity) VALUES (27, 'TOURISME : MANAGEMENT TOURISTIQUE - Niveau 1', 'L1', 14, 50) ON CONFLICT DO NOTHING;
INSERT INTO public.classes (id, name, level, specialty_id, capacity) VALUES (28, 'TOURISME : MANAGEMENT TOURISTIQUE - Niveau 2', 'L2', 14, 50) ON CONFLICT DO NOTHING;
INSERT INTO public.classes (id, name, level, specialty_id, capacity) VALUES (29, 'URBAN PLANNING - Niveau 1', 'L1', 15, 50) ON CONFLICT DO NOTHING;
INSERT INTO public.classes (id, name, level, specialty_id, capacity) VALUES (30, 'URBAN PLANNING - Niveau 2', 'L2', 15, 50) ON CONFLICT DO NOTHING;

-- 3. Insertion des Matières (Échantillon représentatif basé sur vos fichiers Excel)
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (1, 'TOP 111', 'Mathematics I', 4, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (2, 'TOP 1121', 'Physics I', 3, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (3, 'TOP 1122', 'Chemistry', 2, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (4, 'TOP 1131', 'Topometric calculation I', 3, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (5, 'TOP 1132', 'Topometric technology I', 3, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (6, 'TOP 1141', 'Technical drawing I', 2, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (7, 'TOP 1142', 'Cartography I', 2, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (8, 'TOP 1151', 'GPS I', 2, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (9, 'TOP 1152', 'Photogrammetry I', 2, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (10, 'TOP 116', 'Engineering geology / Topology', 4, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (11, 'TOP 1171', 'English', 1, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (12, 'TOP 1172', 'French', 1, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (13, 'TOP 121', 'Mathematics II', 4, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (14, 'TOP 122', 'Computer Science I', 5, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (15, 'TOP 1231', 'GPS II', 2, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (16, 'TOP 1232', 'Photogrammetry II', 2, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (17, 'TOP 1241', 'Technical drawing II', 2, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (18, 'TOP 1242', 'Cartography II', 2, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (19, 'TOP 125', 'Land tenure and estate system', 3, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (20, 'TOP 1261', 'Topometric calculations II', 4, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (21, 'TOP 1262', 'Topometric Technology II', 3, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (22, 'TOP 1271', 'Entrepreneurship', 1, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (23, 'TOP 1272', 'Civic and moral education', 2, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (24, 'TOP 231', 'Mathematics III', 4, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (25, 'TOP 2321', 'Physics III', 2, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (26, 'TOP 2322', 'Chemistry', 2, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (27, 'TOP 2331', 'Geographical Information System', 2, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (28, 'TOP 2332', 'Geographical Information System', 2, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (29, 'TOP 234', 'Topometric calculations III', 4, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (30, 'TOP 235', 'Topometric technology III', 4, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (31, 'TOP 2361', 'Urban development', 3, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (32, 'TOP 2362', 'Computer Assisted Drawing', 3, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (33, 'TOP 2371', 'Initiation to the law', 1, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (34, 'TOP 2372', 'Methodology of writing an internship report', 1, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (35, 'TOP 241', 'Statistics', 4, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (36, 'TOP 242', 'Computer Science II', 5, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (37, 'TOP 2431', 'Topometric calculations IV', 3, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (38, 'TOP 2432', 'Topometric calculations IV', 2, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (39, 'TOP 2441', 'Remote Sensing II', 2, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (40, 'TOP 2442', 'Geodesy', 3, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (41, 'TOP 245', 'Highway systems and various networks (HHT)', 3, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (42, 'TOP 246', 'professional internship I', 6, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (43, 'TOP 2471', 'Accounting', 1, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (44, 'TOP 2472', 'Economics', 2, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (45, 'URP 111', 'Mathematics I', 4, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (46, 'URP 112', 'Physics I', 3, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (47, 'URP 113', 'Chemistry', 2, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (48, 'URP 113', 'Urbanism and town planning regulations', 4, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (49, 'URP 114', 'Subdivision', 4, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (50, 'URP 115', 'Urban road and sanitation I', 5, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (51, 'URP 1161', 'Urban Sociology', 3, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (52, 'URP 1162', 'Urban Habitat', 2, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (53, 'URP 1171', 'English', 1, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (54, 'URP 1172', 'French', 1, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (55, 'URP 121', 'Mathematics II', 4, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (56, 'URP 122', 'Computer Science I', 5, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (57, 'URP 123', 'Computer-assisted cartography', 4, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (58, 'URP 1241', 'Urban Economics', 2, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (59, 'URP 1242', 'Urban Economics', 2, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (60, 'URP 125', 'Knowledge of the environment', 5, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (61, 'URP 126', 'Public and local finance', 5, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (62, 'URP 1271', 'Creation of company', 2, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (63, 'URP 1272', 'Creation of company', 1, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (64, 'URP 231', 'Mathematics III', 4, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (65, 'URP 2321', 'Physics III', 3, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (66, 'URP 2322', 'Chemistry', 2, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (67, 'URP 233', 'Cycle and management of urban projects', 5, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (68, 'URP 2341', 'Site organization', 2, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (69, 'URP 2342', 'Demography', 3, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (70, 'URP 235', 'Photogrammetry and topography', 4, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (71, 'URP 236', 'Urban road and sanitation II', 4, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (72, 'URP 2371', 'Methodology of drafting the internship report', 1, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (73, 'URP 2372', 'Initiation to the law', 1, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (74, 'URP 241', 'Statistics', 4, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (75, 'URP 242', 'Computer Science II', 5, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (76, 'URP 243', 'Site Survey and GPS', 4, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (77, 'URP 244', 'Construction Materials', 3, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (78, 'URP 2451', 'Town planning project', 3, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (79, 'URP 2452', 'Urban transport', 2, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (80, 'URP 246', 'Professional Internship', 6, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (81, 'URP 2471', 'Accounting', 1, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (82, 'URP 2472', 'Economics', 2, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (83, 'CET 111', 'Mathematics I', 4, 3) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (84, 'CET 1121', 'Physics I', 3, 3) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (85, 'CET 1122', 'Chemistry', 2, 3) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (86, 'CET 113', 'Engineering Survey', 3, 3) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (87, 'CET 1141', 'Hydraulics', 2, 3) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (88, 'CET 1142', 'Concrete technology', 3, 3) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (89, 'CET 115', 'Theory of Structures', 4, 3) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (90, 'CET 115', 'Civil Engineering Quantities and Specifications', 4, 3) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (91, 'CET 1171', 'English', 1, 3) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (92, 'CET 1172', 'French', 1, 3) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (93, 'CET 121', 'Mathematics II', 4, 3) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (94, 'CET 122', 'Computer Science I', 5, 3) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (95, 'CET 123', 'Hydrology and Hydrogeology', 5, 3) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (96, 'CET 124', 'Design of Structural Elements', 5, 3) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (97, 'CET 125', 'Construction Technology', 4, 3) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (98, 'CET 126', 'Industrial Management', 4, 3) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (99, 'CET 1271', 'Creation of company', 1, 3) ON CONFLICT DO NOTHING;
INSERT INTO public.subjects (id, code, name, credits, specialty_id) VALUES (100, 'CET 1272', 'Civic and Moral Education', 2, 3) ON CONFLICT DO NOTHING;
