DROP TABLE IF EXISTS public.audit_logs CASCADE;
DROP TABLE IF EXISTS public.official_documents CASCADE;
DROP TABLE IF EXISTS public.disciplinary_actions CASCADE;
DROP TABLE IF EXISTS public.bulletins CASCADE;
DROP TABLE IF EXISTS public.grades CASCADE;
DROP TABLE IF EXISTS public.evaluations CASCADE;
DROP TABLE IF EXISTS public.payroll_slips CASCADE;
DROP TABLE IF EXISTS public.finance_payments CASCADE;
DROP TABLE IF EXISTS public.finance_payment_plans CASCADE;
DROP TABLE IF EXISTS public.finance_student_fees CASCADE;
DROP TABLE IF EXISTS public.finance_fee_types CASCADE;
DROP TABLE IF EXISTS public.whatsapp_notifications CASCADE;
DROP TABLE IF EXISTS public.attendance_records CASCADE;
DROP TABLE IF EXISTS public.attendance_device_logs CASCADE;
DROP TABLE IF EXISTS public.course_schedules CASCADE;
DROP TABLE IF EXISTS public.students CASCADE;
DROP TABLE IF EXISTS public.staff CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;
DROP TABLE IF EXISTS public.roles CASCADE;
DROP TABLE IF EXISTS public.subjects CASCADE;
DROP TABLE IF EXISTS public.classes CASCADE;
DROP TABLE IF EXISTS public.specialties CASCADE;
DROP TABLE IF EXISTS public.semesters CASCADE;
DROP TABLE IF EXISTS public.academic_years CASCADE;
DROP EXTENSION IF EXISTS btree_gist;
DROP EXTENSION IF EXISTS \"uuid-ossp\";
